### ISSUE TITLE
BeautifulSoup ?

### ISSUE THREAD

**Issue by Dom4n** [6IX7ine/djangohunter#1]
Are You sure `BeautifulSoup` package is needed and not `beautifulsoup4` ?

`from bs4 import BeautifulSoup`

**Comment by jimywork** [comment]
I would use to parse the html to grab the information and return it to the user. But I did not do it, you can do it.

**Comment by Dom4n** [comment]
Let me be clear. 
Package `BeautifulSoup` from requirements.txt file is pointing to old version:
https://pypi.org/project/BeautifulSoup/ - 3.2.1 last update was in 2012.
You are importing in code `from bs4...` and I think that You are using version 4:
https://pypi.org/project/beautifulsoup4/

So there is a mistake in requirements file in my opinion.

**Comment by jimywork** [comment]
To resolve this, you can add the version you want to use in the requirements file

BeautifulSoup==4.6.3 
BeautifulSoup>=4.6.3
